### ISSUE TITLE
Example broken by trpc version 10.33.1

### ISSUE THREAD

**Issue by tarehart** [c-ehrlich/msw-trpc-example#1]
Hello, just wanted to let you know that this example no longer works. I filed this issue with trpc: https://github.com/trpc/trpc/issues/5134

As a workaround, you can pin the version to 10.33.0 if you wish.

**Comment by c-ehrlich** [comment]
thanks for the issue and sorry for the late reply

ive updated the example to pass fetch to the httpLink parameter :)
